// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
VAR DoanhSoHienTai = [Doanh số]
VAR DoanhSoCungKy = CALCULATE( [Doanh số], SAMEPERIODLASTYEAR( Dim_Date[Date] ) )
VAR ChenhLech = DoanhSoHienTai - DoanhSoCungKy

Tăng trưởng YoY % = DIVIDE( ChenhLech, DoanhSoCungKy )